"""Partition metadata container for decision variables and constraints.

This module provides the :class:`Partition` class, which is used to map 
semantic names (e.g., "x1", "bounds_u_min") to specific index ranges or 
arrays. It enables cost and constraint factories to perform dynamic column/row 
lookups rather than relying on hardcoded layouts.
"""

from __future__ import annotations

from typing import Dict, Union, Sequence, Optional, Any, Iterable
import jax.numpy as jnp
from jax import Array
import numpy as np


class Partition:
    """A unified container for mapping semantic names to index locations.
    
    This class wraps a dictionary mapping strings to either Python ``slice`` 
    objects or JAX ``Array`` indices. It can be used to partition columns 
    (primal decision variables) or rows (dual constraints). 
    
    By using the :meth:`offset` method, local partitions generated by 
    individual cost or constraint factories can be easily shifted and embedded 
    into the global MPC problem matrices.
    """

    def __init__(self, mapping: Dict[str, Union[slice, Array]]) -> None:
        """Initialize the partition with a structural mapping.
        
        Args:
            mapping: A dictionary mapping string identifiers to 1D index 
                representations (either a ``slice`` or an integer ``Array``).
        """
        self._mapping = mapping

    # ======================================================================
    # Dictionary-like Interface
    # ======================================================================

    def __getitem__(self, key: str) -> Union[slice, Array]:
        return self._mapping[key]

    def get(self, key: str, default: Any = None) -> Any:
        return self._mapping.get(key, default)

    def keys(self) -> Iterable[str]:
        return self._mapping.keys()

    def values(self) -> Iterable[Union[slice, Array]]:
        return self._mapping.values()

    def items(self) -> Iterable[tuple[str, Union[slice, Array]]]:
        return self._mapping.items()

    def __contains__(self, key: str) -> bool:
        return key in self._mapping

    def __len__(self) -> int:
        return len(self._mapping)

    def __repr__(self) -> str:
        return f"Partition({self._mapping!r})"

    # ======================================================================
    # Structural Manipulation
    # ======================================================================

    def offset(self, delta: int) -> Partition:
        """Shift all indices in the partition forward by a flat integer.
        
        This is essential for placing local constraint rows or variable 
        sub-blocks into a larger global matrix layout.
        
        Parameters
        ----------
        delta: The integer offset to add to all slices and arrays.
            
        Returns
        -------
        A new :class:`Partition` instance with the shifted indices.
        """
        new_mapping: Dict[str, Union[slice, Array]] = {}
        for k, v in self._mapping.items():
            if isinstance(v, slice):
                # Ensure start and stop are bounded integers before shifting
                start = v.start + delta if v.start is not None else delta
                stop = v.stop + delta if v.stop is not None else None
                new_mapping[k] = slice(start, stop, v.step)
            else:
                # Handle JAX/NumPy structural index arrays
                new_mapping[k] = v + delta
        return Partition(new_mapping)

    # ======================================================================
    # Factory Methods
    # ======================================================================

    @classmethod
    def state_before_input(
        cls,
        nx: int,
        nu: int,
        N: int,
        state_names: Optional[Sequence[str]] = None,
        input_names: Optional[Sequence[str]] = None,
        keep_x0: bool = False,
    ) -> "Partition":
        """Construct a grouped partition (states followed by controls).
        
        Generates a block-layout partition where all state sequences 
        are placed at the front of the vector, followed immediately by control 
        sequences. Populates global slices (e.g., ``"x"``, ``"u"``), timestep 
        slices (e.g., ``"x1"``, ``"u0"``), and component slices.

        Layouts:
            * ``keep_x0=False``: ``z = [x_1, ..., x_N | u_0, ..., u_{N-1}]``
            * ``keep_x0=True`` : ``z = [x_0, ..., x_N | u_0, ..., u_{N-1}]``
            
        Parameters
        ----------
        nx: Dimension of the state vector.
        nu: Dimension of the control input vector.
        N: The horizon length of the MPC problem.
        state_names: Optional list of strings naming the individual state 
            components (must be length ``nx``). Defaults to indices.
        input_names: Optional list of strings naming the individual control 
            components (must be length ``nu``). Defaults to indices.
        keep_x0: Whether the initial state ``x_0`` is treated as a free 
            decision variable in the state block.
                
        Returns
        -------
        A populated :class:`Partition` instance.
            
        Raises
        ------
        ValueError: If the provided name lists do not match ``nx`` or ``nu``.
        """
        mapping: Dict[str, Union[slice, Array]] = {}

        # 1. Resolve individual component-level coordinate names
        if input_names is not None:
            if len(input_names) != nu:
                raise ValueError(f"input_names length ({len(input_names)}) must match nu ({nu})")
            u_components = list(input_names)
        else:
            u_components = [str(i) for i in range(nu)]

        if state_names is not None:
            if len(state_names) != nx:
                raise ValueError(f"state_names length ({len(state_names)}) must match nx ({nx})")
            x_components = list(state_names)
        else:
            x_components = [str(i) for i in range(nx)]

        # 2. Build State Sequence Block (Front of vector)
        if keep_x0:
            total_x_steps = N + 1
            x_time_indices = range(N + 1)
        else:
            total_x_steps = N
            x_time_indices = range(1, N + 1)

        x_total_dim = total_x_steps * nx
        mapping["x"] = slice(0, x_total_dim)

        for step_idx, t in enumerate(x_time_indices):
            t_start = step_idx * nx
            t_end = (step_idx + 1) * nx
            mapping[f"x{t}"] = slice(t_start, t_end)
            
            # Map specific component states at this timestep
            for i, comp_name in enumerate(x_components):
                key_name = f"x{comp_name}_{t}" if state_names is None else f"{comp_name}{t}"
                mapping[key_name] = slice(t_start + i, t_start + i + 1)

        # 3. Build Control Inputs Block (Back of vector)
        u_start_offset = x_total_dim
        u_total_dim = N * nu
        mapping["u"] = slice(u_start_offset, u_start_offset + u_total_dim)

        for t in range(N):
            t_start = u_start_offset + t * nu
            t_end = u_start_offset + (t + 1) * nu
            mapping[f"u{t}"] = slice(t_start, t_end)
            
            # Map specific component states at this timestep
            for i, comp_name in enumerate(u_components):
                key_name = f"u{comp_name}_{t}" if input_names is None else f"{comp_name}{t}"
                mapping[key_name] = slice(t_start + i, t_start + i + 1)

        return cls(mapping)

    @classmethod
    def dynamics_rows(
        cls,
        nx          : int,
        N           : int,
        state_names : Optional[Sequence[str]] = None,
        cst_name   : str = "dyn"
    ) -> Partition:
        """Construct a row partition for horizon dynamics equality constraints.
        
        In standard multiple-shooting or direct transcription MPC, there are 
        N * nx equality constraints enforcing the system dynamics:
        x_1 = f(x_0, u_0), ..., x_N = f(x_{N-1}, u_{N-1}).
        
        This method maps the rows of this constraint block to their corresponding 
        timesteps and individual state components. Because the dual multipliers 
        of these rows correspond to the costates, they are named using the state 
        convention by default.
        
        Parameters
        ----------
        nx: Dimension of the state vector.
        N: The horizon length of the MPC problem.
        state_names: Optional list of strings naming the individual state 
            components (must be length ``nx``). Defaults to indices.
        cst_name : str, default "dyn"
            A descriptive name of this constraint.
                
        Returns
        -------
        A populated :class:`Partition` instance mapping dynamics rows.
        """
        mapping: Dict[str, Union[slice, Array]] = {}

        # 1. Resolve component names
        if state_names is not None:
            if len(state_names) != nx:
                raise ValueError(f"state_names length ({len(state_names)}) must match nx ({nx})")
            components = list(state_names)
        else:
            components = [str(i) for i in range(nx)]

        # 2. Global block for the entire dynamics sequence
        mapping[cst_name] = slice(0, N * nx)

        # 3. Timestep blocks (1-indexed to match x_1 ... x_N convention)
        for t in range(1, N + 1):
            step_idx = t - 1
            t_start = step_idx * nx
            t_end = t * nx
            mapping[f"{cst_name}_{t}"] = slice(t_start, t_end)

            # 4. Component-level blocks
            for i, comp_name in enumerate(components):
                # E.g., custom: "pos1", default: "x0_1"
                key_name = f"{cst_name}_{comp_name}_{t}" if state_names is None else f"{comp_name}{t}"
                mapping[key_name] = slice(t_start + i, t_start + i + 1)

        return cls(mapping)

    @classmethod
    def box_rows(
        cls,
        mask : Union[np.ndarray, Array],
        nx   : int,
        nu   : int,
        N    : int,
    ) -> Partition:
        """Construct a row partition for compressed box constraints.
        
        Because infinite bounds are dropped from the constraint matrix, this 
        method maps the surviving rows to their semantic names using the boolean 
        mask. It intelligently collapses contiguous rows back into `slice` objects 
        for optimal JAX performance.
        
        Parameters
        ----------
        mask: A 1D boolean array of length 2*N*nx + 2*N*nu indicating which 
            rows were kept in the global box formulation.
        nx: Dimension of the state vector.
        nu: Dimension of the control input vector.
        N: The horizon length.
            
        Returns
        -------
        A populated :class:`Partition` instance.
        """
        
        # 1. Create a mapping from unmasked row indices to compressed row indices
        mask_np = np.asarray(mask, dtype=bool)
        new_row_indices = np.full(len(mask_np), -1)
        new_row_indices[mask_np] = np.arange(np.sum(mask_np))
        
        mapping: Dict[str, Union[slice, Array]] = {}
        
        # Helper to convert indices to a slice if contiguous, or Array if fragmented
        def _to_slice_or_array(idx: np.ndarray) -> Union[slice, Array]:
            if len(idx) == 0:
                return slice(0, 0)
            if len(idx) == 1:
                return slice(int(idx[0]), int(idx[0] + 1))
            if np.all(np.diff(idx) == 1):
                return slice(int(idx[0]), int(idx[-1] + 1))
            return jnp.asarray(idx)

        # The global unmasked layout built by `build_box_lhs`
        blocks = [
            ("x_max", nx),
            ("x_min", nx),
            ("u_max", nu),
            ("u_min", nu),
        ]
        
        current_offset = 0
        
        for base_name, dim in blocks:
            block_size = N * dim
            unmasked_range = np.arange(current_offset, current_offset + block_size)
            
            # 2. Map the global block (e.g., "x_max")
            valid_mask = mask_np[unmasked_range]
            valid_new_indices = new_row_indices[unmasked_range[valid_mask]]
            
            if len(valid_new_indices) > 0:
                mapping[base_name] = _to_slice_or_array(valid_new_indices)
            
            # 3. Map the individual timesteps (e.g., "x_max1", "u_min0")
            is_state = base_name.startswith("x")
            for t in range(N):
                step_suffix = str(t + 1) if is_state else str(t)
                step_range = unmasked_range[t * dim : (t + 1) * dim]
                
                valid_step_mask = mask_np[step_range]
                valid_step_indices = new_row_indices[step_range[valid_step_mask]]
                
                if len(valid_step_indices) > 0:
                    mapping[f"{base_name}_{step_suffix}"] = _to_slice_or_array(valid_step_indices)
                    
            current_offset += block_size
            
        return cls(mapping)